version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  api_gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - OTLP_EXPORTER_ENDPOINT=http://jaeger:4317
      - SERVICE_NAME=api-gateway
    depends_on:
      - jaeger
      - inventory_service
      - order_service
      - notification_service

  inventory_service:
    build: ./inventory-service
    environment:
      - OTLP_EXPORTER_ENDPOINT=http://jaeger:4317
      - SERVICE_NAME=inventory-service

  order_service:
    build: ./order-service
    environment:
      - OTLP_EXPORTER_ENDPOINT=http://jaeger:4317
      - SERVICE_NAME=order-service

  notification_service:
    build: ./notification-service
    environment:
      - OTLP_EXPORTER_ENDPOINT=http://jaeger:4317
      - SERVICE_NAME=notification-service
